### ISSUE TITLE
WMS Image Decoding

### ISSUE THREAD

**Issue by ingalls** [developmentseed/ml-enabler#178]
```
[ERROR] UnidentifiedImageError: cannot identify image file <_io.BytesIO object at 0x7fd1d1af94f0>
Traceback (most recent call last):
  File "/var/task/download_and_predict/handler.py", line 45, in handler
    payload = dap.get_prediction_payload(t_i)
  File "/var/task/download_and_predict/tensorflow.py", line 122, in get_prediction_payload
    img_l.append(self.listencode_image(img))
  File "/var/task/download_and_predict/tensorflow.py", line 84, in listencode_image
    img = Image.open(io.BytesIO(image))
  File "/tmp/pip-target-clrrjnqf/lib/python/PIL/Image.py", line 2943, in open
```

**Comment by ingalls** [comment]
Fixed!
